// <auto-generated />
using MainAliRezaMain.BackEnd;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MainAliRezaMain.Migrations
{
    [DbContext(typeof(ConnectingDB))]
    [Migration("20190706152954_reza")]
    partial class reza
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MainAliRezaMain.BackEnd.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Birthday_Day");

                    b.Property<string>("Birthday_Month");

                    b.Property<string>("Birthday_Year");

                    b.Property<string>("E_Mail");

                    b.Property<string>("FirstName");

                    b.Property<string>("Gender");

                    b.Property<string>("LastName");

                    b.Property<string>("Mobil");

                    b.Property<string>("PassWord");

                    b.Property<string>("Picture");

                    b.Property<string>("Sath_E_Dastresy");

                    b.Property<string>("Telephon");

                    b.Property<string>("UserName");

                    b.HasKey("ID");

                    b.ToTable("person1");
                });

            modelBuilder.Entity("MainAliRezaMain.BackEnd.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brand");

                    b.Property<string>("Category");

                    b.Property<string>("Mojody_Anbar");

                    b.Property<string>("Name");

                    b.Property<string>("Picture");

                    b.Property<string>("Price");

                    b.Property<string>("Weight");

                    b.HasKey("ID");

                    b.ToTable("product1");
                });

            modelBuilder.Entity("MainAliRezaMain.BackEnd.ProductGE", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("General_Explanation");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("productGEs");
                });

            modelBuilder.Entity("MainAliRezaMain.BackEnd.SaveShoppingCartToDB", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PayingByWhichBank");

                    b.Property<string>("PersonID");

                    b.Property<string>("PersonName");

                    b.Property<string>("PersonPass");

                    b.Property<string>("PersonUser");

                    b.Property<string>("ProductName");

                    b.Property<string>("ProductPrice");

                    b.HasKey("ID");

                    b.ToTable("saveShoppingCartToDBs");
                });
#pragma warning restore 612, 618
        }
    }
}
